name: intake-esgf-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pandas
  - dask
  - xarray
  - netCDF4
  - globus-sdk
  - requests
  - tqdm[notebook]
  - pyyaml
  - jupyterlab
  - matplotlib
  - pytest
  - pytest-cov
  - pre-commit
